name = "Quote App"
client_id = ""
application_url = "https://localhost/app"
embedded = true
extension_directories = ["storefront/extension"]

[access_scopes]
scopes = "write_draft_orders,read_draft_orders,write_orders,read_orders,read_products,read_customers,write_customers"

[auth]
redirect_urls = ["https://localhost/auth/shopify/callback"]

[app_proxy]
url = "https://localhost/api/storefront"
prefix = "apps"
subpath = "quote"

[webhooks]
api_version = "2025-07"

[[webhooks.subscriptions]]
topics = ["draft_orders/create", "draft_orders/update", "orders/create", "app/uninstalled"]
uri = "/api/webhooks"
