# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1ca9359d26e9fc0fc76367b6bb8feb40"
name = "Claude Quote AI"
application_url = "https://quote-claude.local"
embedded = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/api/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,read_products,write_draft_orders"

[auth]
redirect_urls = [ "https://quote-claude.local" ]

extension_directories = [ "extensions/quote-storefront" ]
